LoginPoC/LoginPoC.Web/Areas/Common/Models/ProcessViewModel.cs
using LoginPoC.Model.Process;
using LoginPoC.Model.ProcessType;
using LoginPoC.Model.User;
using System;
using System.Collections.Generic;
using System.Web;

namespace LoginPoC.Web.Areas.Common.Models
{
    public class ProcessViewModel
    {
        public int Id { get; set; }
        public ProcessType Type { get; set; }
        public DateTime CreationDate { get; set; }
        public string Status { get; set; }
        public string ReviewNotes { get; set; }
        public DateTime? ReviewDate { get; set; }
        public ApplicationUser AssignedAgent { get; set; }
        public ApplicationUser Creator { get; set; }

        public IEnumerable<ProcessFieldViewModel> Fields { get; set; }
        public IEnumerable<ProcessDocument> Documents { get; set; }
    }
}

LoginPoC/LoginPoC.Web/Areas/Common/Controllers/ProcessController.cs
using AutoMapper;
using LoginPoC.Core.Process;
using LoginPoC.Core.ProcessType;
using LoginPoC.Core.User;
using LoginPoC.Model.Process;
using LoginPoC.Model.ProcessType;
using LoginPoC.Model.User;
using LoginPoC.Web.Areas.Common.Models;
using LoginPoC.Web.Helpers;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LoginPoC.Web.Areas.Common.Controllers
{
	[Authorize]
	public class ProcessController : Controller
	{
		private IProcessTypeService ProcessTypeService { get; set; }
		private IProcessService ProcessService { get; set; }
		private ICountryService CountryService { get; set; }
		private IMapper Mapper { get; set; }

		public ProcessController(
			IProcessTypeService processTypeService, 
			IProcessService processService,
			ICountryService countryService, 
			IMapper mapper)
		{
			this.ProcessTypeService = processTypeService;
			this.ProcessService = processService;
			this.CountryService = countryService;
			this.Mapper = mapper;
		}

		// GET: Process
		[OverrideAuthorization]
		[Authorize(Roles = ApplicationUserRoles.Agent + ", " + ApplicationUserRoles.Administrator)]
		public async Task<ActionResult> Index(string name = null)
		{
			var processes = (await this.ProcessService.SearchNotDraftAsync(name))
													  .ToList();
			processes.Sort(ByStatusAndDate);

			var vm = new ProcessIndexViewModel()
			{
				Processes = processes.Select(x => Mapper.Map<ProcessViewModel>(x)),
				SearchByName = name
			};

			return View(vm);
		}

		// GET: Process
		public async Task<ActionResult> MyProcesses(string name = null)
		{
			var processes = await this.ProcessService.SearchMyProcessesAsync(name, User.Identity.GetUserId());
			var processTypes = await this.ProcessTypeService.SearchAsync(null, User.Identity.GetUserId());
			var vm = new ProcessIndexViewModel()
			{
				Processes = processes.Select(x => Mapper.Map<ProcessViewModel>(x)),
				ProcessTypes = processTypes,
				SearchByName = name
			};

			return View(vm);
		}

		public async Task<ActionResult> Edit(int id)
		{
			var process = this.ProcessService.GetById(id);
			ProcessViewModel model = Mapper.Map<ProcessViewModel>(process);

			await FillSelectLists(process, model);

			return View(model);
		}

		// POST: Process/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		public ActionResult Edit(ProcessViewModel process)
		{
			if (!ModelState.IsValid || process.Id == 0)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ModelState.AllErrorsToString());
			}

			Process model = Mapper.Map<Process>(process);
			this.ProcessService.Update(model);
			process = Mapper.Map<ProcessViewModel>(model);

			return this.JsonNet(process);
		}

		public async Task<ActionResult> Create(int Id)
		{
			var process = await this.ProcessService.GetByTypeAsync(Id, User.Identity.GetUserId());
			ProcessViewModel model = Mapper.Map<ProcessViewModel>(process);

			await FillSelectLists(process, model);

			List<ProcessDocument> documents = new List<ProcessDocument>();
			foreach (var item in process.Documents)
			{
				documents.Add(Mapper.Map<ProcessDocument>(item));
			}

			return View("Edit", model);
		}

		private async Task FillSelectLists(Process process, ProcessViewModel model)
		{
			foreach (var item in process.Fields)
			{
				switch (item.Type)
				{
					case FieldType.Gender:
						model.Fields.Single(f => f.Type == item.Type.ToString()).SelectList = EnumHelper<Gender>.AsKeyValuePairs();
						break;
					case FieldType.MaritalStatus:
						model.Fields.Single(f => f.Type == item.Type.ToString()).SelectList = EnumHelper<MaritalStatus>.AsKeyValuePairs();
						break;
					case FieldType.Country:
						var countryList = new List<KeyValuePair<int, string>>();
						var countries = await this.CountryService.GetCountriesAsync();
						foreach (Country country in countries)
						{
							countryList.Add(Mapper.Map<KeyValuePair<int, string>>(country));
						}

						model.Fields.Single(f => f.Type == item.Type.ToString()).SelectList = countryList;
						break;                    
					default:
						break;
				}
			}
			}

		// POST: Process/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		public ActionResult Create(ProcessViewModel process)
		{
			if (!ModelState.IsValid)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ModelState.AllErrorsToString());
			}

			if (process.Id != 0)
			{
				return new HttpStatusCodeResult(HttpStatusCode.Conflict);
			}

			Process model = Mapper.Map<Process>(process);
			this.ProcessService.Add(model, User.Identity.GetUserId());
			process = Mapper.Map<ProcessViewModel>(model);

			return this.JsonNet(process);
		}

		// GET: Process/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			Process process = this.ProcessService.GetById(id.Value);
			if (process == null)
			{
				return HttpNotFound();
			}

			ProcessViewModel model = Mapper.Map<ProcessViewModel>(process);
			return View(model);
		}

		// POST: Process/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			this.ProcessService.Delete(id);
			return RedirectToAction("MyProcesses");
		}

		// GET: Process/Assign/{id}?userId={userId}
		public async Task<ActionResult> Assign(int id, string userId)
		{
			await this.ProcessService.AssignAgentAsync(id, userId);
			return Redirect(this.Request.UrlReferrer.ToString());
		}

		// GET: Process/Deassign/{id}
		public async Task<ActionResult> Deassign(int id)
		{
			await this.ProcessService.DeassignAsync(id);
			return Redirect(this.Request.UrlReferrer.ToString());
		}

		// POST: Process/Send/{id}
		[HttpPost]
		public async Task<ActionResult> Send(int id)
		{
			await this.ProcessService.ChangeStatusAsync(id, ProcessStatus.Submitted);
			return this.JsonNet(new { ok = true });
		}

		// POST: Process/Approve/{id}
		[HttpPost]
		public async Task<ActionResult> Approve(int id, string reviewNotes)
		{
			await this.ProcessService.ChangeStatusAsync(id, ProcessStatus.Approved, reviewNotes);
			return this.JsonNet(new { ok = true });
		}

		// POST: Process/Reject/{id}
		[HttpPost]
		public async Task<ActionResult> Reject(int id, string reviewNotes)
		{
			await this.ProcessService.ChangeStatusAsync(id, ProcessStatus.Rejected, reviewNotes);
			return this.JsonNet(new { ok = true });
		}

		private int ByStatusAndDate(Process a, Process b)
		{
			if (a.Status == b.Status)
			{
				if (a.AssignedAgentId == this.User.Identity.GetUserId<string>() && b.AssignedAgentId == this.User.Identity.GetUserId<string>())
					return a.CreationDate.CompareTo(b.CreationDate);

				if (a.AssignedAgentId == this.User.Identity.GetUserId<string>())
					return -1;
				
				if (b.AssignedAgentId == this.User.Identity.GetUserId<string>())
					return 1;

				if (a.AssignedAgentId != null && b.AssignedAgent != null)
					return a.CreationDate.CompareTo(b.CreationDate);

				if (a.AssignedAgentId == null)
					return -1;

				if (b.AssignedAgentId != null)
					return 1;
			}

			return a.Status.CompareTo(b.Status);
		}

		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
	}
}

LoginPoC/LoginPoC.Web/Areas/Common/Views/Process/Delete.cshtml
@model LoginPoC.Web.Areas.Common.Models.ProcessViewModel

@{
    ViewBag.Title = "Eliminar Trámite";
}

<h2 class="tituloPrincipal readable">@ViewBag.Title</h2>
<hr class="tituloPrincipal readable" />
<h3 class="readable">&iquest;Est&aacute; seguro de eliminar el tr&aacute;mite?</h3>
<div>

    <dl class="dl-horizontal">
        <dt class="readable">
            Fecha de Creaci&oacute;n
            <!--@Html.DisplayNameFor(model => model.CreationDate)-->
        </dt>
        <dd class="readable">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class="readable">
            Notas de Revisi&oacute;n
            <!--@Html.DisplayNameFor(model => model.ReviewNotes)-->
        </dt>
        <dd class="readable">
            @Html.DisplayFor(model => model.ReviewNotes)
        </dd>
        <dt class="readable">
            Fecha de Revisi&oacute;n
            <!--@Html.DisplayNameFor(model => model.ReviewDate)-->
        </dt>
        <dd class="readable">
            @Html.DisplayFor(model => model.ReviewDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="submit" value="Eliminar" class="btn btn-satia btn-rechazar readable">Eliminar</button>
            <a href="@Url.Action("MyProcesses")" class="btn btn-satia btn-secundario readable">Volver</a>
        </div>
    }
</div>

LoginPoC/LoginPoC.Web/Areas/Common/Views/Process/Edit.cshtml
@using LoginPoC.Model.User
@using LoginPoC.Model.Process
@using Microsoft.AspNet.Identity
@using LoginPoC.Web.Areas.Common.Models
@using Newtonsoft.Json
@model ProcessViewModel

@{
    var jsonModel = JsonConvert.SerializeObject(Model);
    ViewBag.Title = "Trámite";
    var enableEdit = this.User.IsInRole(ApplicationUserRoles.User);
    var enableReview = (this.User.IsInRole(ApplicationUserRoles.Agent) && Model.AssignedAgent?.Id == User.Identity.GetUserId<string>())
                    || this.User.IsInRole(ApplicationUserRoles.Administrator);
}

<div ng-controller="Process.Edit" ng-init='events.onInit(@Html.Raw(jsonModel), @enableEdit.ToString().ToLower(), @enableReview.ToString().ToLower())'>
    <h2 class="tituloPrincipal readable"> {{ process.type.name }} </h2>
    <hr class="tituloPrincipal" />
    <div class="row">   
        <div class="col-md-offset-2 col-md-8 tramite-seccion readable">Formulario</div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>        
        <div class="col-md-8">
            <div ng-repeat="field in process.fields track by $index" class="col-md-6 tramite-campo">
                <label class="readable">
                    {{ field.name }}
                </label>
                <sup style="top:-1em"><span class="fa fa-asterisk" ng-if="field.isRequired" style="color: #D92020; font-size:8px;"></span></sup>
                <input ng-model="field.value" class="form-control" type="{{ inputType(field) }}" ng-if="simpleInputType(field.type)" ng-disabled="!editEnabled"/>

                <div class="input-group" ng-if="dateInputType(field.type)">
                    <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
                    <input ng-model="field.value" class="form-control" type="text" date-range-picker options="datePickerOptions" placeholder="dd/mm/aaaa" ng-disabled="!editEnabled" />
                </div>

                <input ng-model="field.value" class="form-control" type="{{ inputType(field) }}" step="0.01" ng-if="stepInputType(field.type)" ng-disabled="!editEnabled">
                <input non-digit-input ng-model="field.value" class="form-control" type="{{ inputType(field) }}" ng-if="noNumbersInputType(field.type)" ng-disabled="!editEnabled">
                <textarea ng-model="field.value" class="form-control" ng-if="textAreaType(field.type)" ng-disabled="!editEnabled"></textarea>
                <select ng-model="field.selectedValue" ng-change="setSelectedValue(field)" ng-options="item as item.value for item in field.selectList track by item.key" class="form-control" ng-if="selectType(field.type)" ng-disabled="!editEnabled"></select>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <p  class="readable" ng-if="completionError" style="color: #D92020">
                Los siguientes campos son requeridos:
                <div class="readable" ng-repeat="field in uncompleteRequiredFields track by $index" style="color: #D92020">
                    {{ field.name | uppercase }}
                </div>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-2 col-md-8 tramite-seccion readable">Documentos</div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div ng-repeat="document in process.documents track by $index" class="col-md-6">
                <label class="readable">
                    <input ng-model="document.isAvailable" class="checkboxEdit" type="checkbox" ng-disabled="!editEnabled" />
                    {{ document.name }}
                </label>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>

    <div class="row" ng-show="reviewEnabled || !!process.reviewNotes">
        <div class="col-md-offset-2 col-md-8 tipoTramite-seccion readable">Observaciones</div>
        <div class="col-md-offset-2 col-md-8">
            <textarea class="form-control readable" ng-model="process.reviewNotes" ng-disabled="!reviewEnabled"></textarea>
        </div>
    </div>

    <div class="row" style="margin-bottom:20px">
    <hr />

        <div class="text-center" ng-if="reviewEnabled">
            <button class="btn btn-satia btn-rechazar readable" ng-click="events.onRejectClicked();">Rechazar</button>
            <button class="btn btn-satia btn-aprobar readable" ng-click="events.onApproveClicked();">Aprobar</button>
        </div>

        <div class="text-center" ng-if="editEnabled">
            <button class="btn btn-satia btn-secundario readable" ng-click="events.onSaveClicked();">Guardar Cambios</button>
            <button class="btn btn-satia btn-primario readable" ng-click="events.onSendToReviewClicked();">Enviar a revisi&oacute;n</button>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/Site/Process/Process.Edit.js"></script>
    <script src="~/Scripts/Site/Angular-Extras/Directives/non-digit-input.js"></script>
}

LoginPoC/LoginPoC.Web/Areas/Common/Views/Process/Index.cshtml
@using LoginPoC.Web.Areas.Common.Models;
@using Microsoft.AspNet.Identity
@using LoginPoC.Model.User
@model ProcessIndexViewModel

@{
    ViewBag.Title = "Trámites";
}

<h2 class="tituloPrincipal">@ViewBag.Title</h2>
<hr class="tituloPrincipal" />
<div class="row">
    @using (Html.BeginForm("Index", "Process", FormMethod.Get, new { area = "Common" }))
    {
        <div class="col-xs-offset-2 col-xs-8 tipoTramite-buscar">
            <input type="text" placeholder="Buscar trámite" name="name" id="name" value="@Model.SearchByName" />
            <button type="submit" class="fa fa-search"></button>
        </div>
    }
</div>
<br />
<div class="row listado">
    @foreach (var item in Model.Processes)
    {
        <div class="col-xs-offset-2 col-xs-8">
            <p class="tipoTramite-item">

                @{  
                    var status = "fa-circle-o";
                    var title = "Pendiente";
                    var estilo = "";
                    if (item.Status == LoginPoC.Model.Process.ProcessStatus.Approved.ToString())
                    {
                        status = "fa-check-circle";
                        estilo = "color: green";
                        title = "Aprobado";
                    }
                    else if (item.Status == LoginPoC.Model.Process.ProcessStatus.Rejected.ToString())
                    {
                        status = "fa-times-circle";
                        title = "Rechazado";
                        estilo = "color: red";
                    }
                    else if (item.Status == LoginPoC.Model.Process.ProcessStatus.Archived.ToString())
                    {
                        status = "fa-ban";
                        title = "Archivado";
                    }
                }

                <span class="tipoTramite-nombre" style="cursor: pointer;">
                    <span class="fa @status" style="vertical-align: middle; @estilo" title="@title"></span> @item.Type.Name - @item.Creator.FirstName @item.Creator.LastName
                </span>
        
                @if (this.User.IsInRole(ApplicationUserRoles.Agent))
                {
                    if (item.AssignedAgent?.Id == User.Identity.GetUserId<string>())
                    {
                    <a href="@Url.Action("Deassign", new { id = item.Id })"><span class='badge pull-right' style="background-color: #fff; color: #777; margin-left: 10px;">Desasignarme</span></a>
                    }
                    else if (item.AssignedAgent == null)
                    {
                    <a href="@Url.Action("Assign", new { id = item.Id, userId = this.User.Identity.GetUserId<string>() })"><span class='badge pull-right' style="background-color: #0095c1; margin-left: 10px;">Asignarme</span></a>   
                    }
                }
                <a href="@Url.Action("Edit", new { id = item.Id })"><span class='fa fa-eye tipoTramite-itemBtn'></span></a>
            </p>
            <div hidden class="tipoTramite-descripcion" id="tipoTramite-@item.Id">
                <p class="tipoTramite-descripcion">
                    @item.Status
                </p>
                <p class="tipoTramite-descripcion">
                    <a href="@Url.Action("Details",new { id = item.Id })">Ver Detalles del trámite</a>
                </p>
            </div>
        </div>
    }
</div>
@section Scripts{
    
}

LoginPoC/LoginPoC.Web/Areas/Common/Views/Process/MyProcesses.cshtml
@using LoginPoC.Web.Areas.Common.Models;
@using Newtonsoft.Json
@model ProcessIndexViewModel
@{
    var jsonModel = JsonConvert.SerializeObject(Model);
    ViewBag.Title = "Mis Tramites";
}

<h2 class="tituloPrincipal readable">Mis tr&aacute;mites guardados</h2>
<hr class="tituloPrincipal" />
<div ng-controller="Process.Index" ng-init='events.onInit(@Html.Raw(jsonModel))'>
    <div class="row">
        @using (Html.BeginForm("MyProcesses", "Process", FormMethod.Get, new { area = "Common" }))
        {
            <div class="col-xs-6 tipoTramite-buscar">
                <input type="text" placeholder="Buscar trámite" name="name" id="name" value="@Model.SearchByName" />
                <button type="submit" class="fa fa-search"></button>
            </div>
        }
        <div class="col-xs-6 tipoTramite-buscar">
            <select name="filteredStatus" ng-model="filtered.status">
                <option value="" style="color:#C7C7CD">Filtrar Estado de Tr&aacute;mites</option>
                <option value="Draft">Borrador</option>
                <option value="Approved">Aprobado</option>
                <option value="Submitted">Enviado</option>
                <option value="Archived">Archivado</option>
                <option value="Rejected">Rechazado</option>
            </select>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <table class="table-striped tabla-tramitesGuardados" style="width:100%">
                <thead>
                    <tr>
                        <td class="readable" width="10%" ng-show="anyDeprecated()"></td>
                        <th class="readable" width="40%">Tr&aacute;mite</th>
                        <th class="readable" width="25%">Fecha de creaci&oacute;n</th>
                        <th class="readable" width="15%">Estado</th>
                        <th class="readable" width="5%">Editar</th>
                        <th class="readable" width="5%">Borrar</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="process in processes | filter:filtered:strict">
                        <td width="10%" ng-if="anyDeprecated()">
                            <div class="readable" ng-hide="process.type.isActive">DEPRECADO</div>
                        </td>
                        <td class="readable" width="40%" style="font-family:GoboldRegular">{{ process.type.name }}</td>
                        <td class="readable" width="25%">{{ process.creationDate | date : "dd/MM/yyyy h:mm a" }}</td>
                        <td class="readable" width="15%">{{ getStatusLabel(process.status) }}</td>
                        <td class="readable" width="5%" class="text-center">
                            @{
                                var editUrl = Url.Action("Edit", new { id = "{{process.id}}" });
                                editUrl = HttpUtility.UrlDecode(editUrl);
                            }
                            <a data-ng-href="@editUrl"><span class='fa tipoTramite-itemBtn' ng-class="{ 'fa-pencil': process.status == 'Draft' || process.status == 'Rejected', 'fa-eye' : process.status == 'Approved' || process.status == 'Submitted' }"></span></a>
                        </td>
                        <td width="5%" class="text-center">
                            @{
                                var deleteUrl = Url.Action("Delete", new { id = "{{process.id}}" });
                                deleteUrl = HttpUtility.UrlDecode(deleteUrl);
                            }
                            <a href="@deleteUrl"><span class='fa fa-trash tipoTramite-itemBtn'></span></a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/Site/Process/Process.Index.js"></script>
}