LoginPoC/LoginPoC.Web/Areas/Admin/Controllers/ProcessTypeController.cs
using LoginPoC.Core.ProcessType;
using LoginPoC.Model.ProcessType;
using LoginPoC.Model.User;
using LoginPoC.Web.Areas.Admin.Models;
using LoginPoC.Web.Helpers;
using Microsoft.AspNet.Identity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LoginPoC.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = ApplicationUserRoles.Agent + ", " + ApplicationUserRoles.Administrator)]
    public class ProcessTypeController : Controller
    {
        // GET DbContext from container
        private IProcessTypeService ProcessTypeService { get; set; }

        public ProcessTypeController(IProcessTypeService processTypeService)
        {
            this.ProcessTypeService = processTypeService;
        }

        // GET: ProcessType
        [OverrideAuthorization]
        [Authorize]
        public async Task<ActionResult> Index(string name = null)
        {
            var processTypes = await this.ProcessTypeService.SearchAsync(name, User.Identity.GetUserId());
            var vm = new ProcessTypeIndexViewModel()
            {
                ProcessTypes = processTypes,
                SearchByName = name
            };

            return View(vm);
        }

        // GET: ProcessType/Details/5
        [OverrideAuthorization]
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ProcessType processType = this.ProcessTypeService.GetById(id.Value);
            if (processType == null)
            {
                return HttpNotFound();
            }
            return View(processType);
        }

        // GET: ProcessType/Create
        public ActionResult Create()
        {
            return View("Edit");
        }

        // POST: ProcessType/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(ProcessType processType)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ModelState.AllErrorsToString());
            }

            if(processType.Id != 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Conflict);
            }

            this.ProcessTypeService.Add(processType);

            return this.JsonNet(processType);
        }

        // GET: ProcessType/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ProcessType processType = this.ProcessTypeService.GetById(id.Value);
            if (processType == null)
            {
                return HttpNotFound();
            }
            return View(processType);
        }

        // POST: ProcessType/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(ProcessType processType)
        {
            if (!ModelState.IsValid || processType.Id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ModelState.AllErrorsToString());
            }

            this.ProcessTypeService.Update(processType);
            return this.JsonNet(processType);
        }

        // GET: ProcessType/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ProcessType processType = this.ProcessTypeService.GetById(id.Value);
            if (processType == null)
            {
                return HttpNotFound();
            }

            return View(processType);
        }

        // POST: ProcessType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            this.ProcessTypeService.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

LoginPoC/LoginPoC.Web/Areas/Admin/Views/ProcessType/Create.cshtml
@model LoginPoC.Model.ProcessType.ProcessType

@{
    ViewBag.Title = "Crear Tramite";
}

<h2 class="tituloPrincipal">Tipos de Tr&aacute;mite</h2>
<hr class="tituloPrincipal" />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Material de Soporte</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            VideoTutorial
            <div class="col-md-10">
                <input type="file" />
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <h4>Formulario</h4>
        <hr />
        Paso 1 <br />
            Preguntas
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LoginPoC/LoginPoC.Web/Areas/Admin/Views/ProcessType/Delete.cshtml
@model LoginPoC.Model.ProcessType.ProcessType

@{
    ViewBag.Title = "Delete";
}

<h2 class="tituloPrincipal">Eliminar Tipo de Tr&aacute;mite</h2>
<hr class="tituloPrincipal" />
<h3>&iquest;Seguro desea eliminar el tipo de tr&aacute;mite?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>Nombre
            <!--@Html.DisplayNameFor(model => model.Name)-->
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Descripci&oacute;n
            <!--@Html.DisplayNameFor(model => model.Description)-->
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-satia btn-rechazar" /> 
            <a href="@Url.Action("Index")" class="btn btn-satia btn-secundario">Cancelar</a>
        </div>
    }
</div>

LoginPoC/LoginPoC.Web/Areas/Admin/Views/ProcessType/Details.cshtml
@using LoginPoC.Model.User
@model LoginPoC.Model.ProcessType.ProcessType

@{
    ViewBag.Title = "Details";
}

<h2 class="tituloPrincipal readable">Detalles de Tipo de Tr&aacute;mite</h2>
<hr class="tituloPrincipal" />
<div>
    <dl class="dl-horizontal tipoTramite-detalles">
        <dt class="readable">
            Nombre
            <!--@Html.DisplayNameFor(model => model.Name)-->
        </dt>
        <dd class="readable">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="readable">
            Descripci&oacute;n
            <!--@Html.DisplayNameFor(model => model.Description)-->
        </dt>
        <dd class="readable">
            <pre style="white-space: pre-wrap;"> @Html.DisplayFor(model => model.Description)</pre>
        </dd>
        <dt class="readable">
            VideoTutorial
        </dt>
        <dd>
            @if (!string.IsNullOrEmpty(Model.URLVideo))
            {
                <iframe width="427" height="240" src="@Html.DisplayFor(model => model.URLVideo)" frameborder="0" allowfullscreen></iframe>
            }
            else
            {
                <span class="readable">Sin VideoTutorial</span>
            }
            
        </dd>

    </dl>
</div>
<div class="row" style="margin-bottom:30px;">
    <div class="col-xs-offset-2 col-xs-1 text-center">
        @if (User.IsInRole(ApplicationUserRoles.Agent) || User.IsInRole(ApplicationUserRoles.Administrator))
        {
            @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-satia btn-primario" })
        }
        
        @if (User.IsInRole(ApplicationUserRoles.User))
        {
            <a href="@Url.Action("Create", "Process", new { area = "Common", id = Model.Id } )" class="readable btn btn-satia btn-primario pull-right">Iniciar tramite</a>
        }
    </div>
    <div class="col-xs-1 text-center readable">
        @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-satia btn-secundario" })
    </div>
</div>

LoginPoC/LoginPoC.Web/Areas/Admin/Views/ProcessType/Edit.cshtml
@using LoginPoC.Model.ProcessType
@using LoginPoC.Web.Areas.Common.Models
@using Newtonsoft.Json
@using LoginPoC.Web.Helpers

@model LoginPoC.Model.ProcessType.ProcessType
@{
    var jsonModel = JsonConvert.SerializeObject(Model);
    var fieldTypes = JsonConvert.SerializeObject(EnumHelper<FieldType>.AsKeyValuePairs());

    ViewBag.Title = string.Format("{0} - {1}", "Tipo de trámite", Model != null ? Model.Name : "Nuevo");
}

<h2 class="tituloPrincipal">Tipo de Tr&aacute;mite</h2>
<hr class="tituloPrincipal" />
<div ng-controller="ProcessType.Edit" ng-init='events.onInit(@Html.Raw(jsonModel), @Html.Raw(fieldTypes))'>
    <form name='myform'>
        <div class="form-horizontal">
            <div class="form-group row">
                <div class="col-md-offset-2 col-md-8 tipoTramite-seccion">Nombre del Tr&aacute;mite</div>
                <div class="col-md-offset-2 col-md-8 tipoTramite-campo">
                    <input ng-model="processType.name"
                           class="form-control" type="text" name="name"
                           required
                           uib-popover="El nombre del tipo de documento es requerido" popover-trigger="'mouseenter'"
                           placeholder="Ingrese el nombre del tramite" />

                </div>
                <div class="col-md-offset-2 col-md-8 tipoTramite-seccion">Material de Soporte</div>
                <div class="col-md-offset-2 col-md-8 tipoTramite-campo">
                    <label>Información adicional</label>
                    <textarea ng-model="processType.description"
                              class="form-control" type="text" name="description"
                              required
                              uib-popover="La descripcion del tipo de trámite es requerido" popover-trigger="'mouseenter'"
                              placeholder="Ingrese información adicional para asistir al usuario en el llenado del tramite">
                </textarea>
                </div>
                <div class="col-md-offset-2 col-md-8 tipoTramite-campo">
                    <label>Video Instructivo</label>
                    <input ng-model="processType.urlVideo"
                           class="form-control" type="text" name="name"
                           uib-popover="Ingresar la URL del videotutorial de Youtube"
                           placeholder="Ingrese la URL del video" />

                </div>
                <div class="col-md-offset-2 col-md-8 tipoTramite-campo">
                    <label style="width: 100%">
                        <input ng-model="processType.isAvailable" ng-disabled="!editAvailable"
                               type="checkbox" name="isAvailable" class="checkboxEdit"/>
                        Disponible para tramitante
                    </label>
                </div>
                <div>
                    <div class="col-md-offset-2 col-md-8 tipoTramite-seccion">Formulario</div>
                    <div class="col-md-offset-2 col-md-8 tipoTramite-campo">
                        <label>Campos</label>
                        <hr style="margin-top:0"/>
                    </div>
                    <div ng-repeat="field in processTypeFields track by $index">
                        <div class="col-md-offset-2 col-md-8 tipoTramite-campo">
                            <div class="col-md-4">
                                <input ng-model="field.name" ng-disabled="!editAvailable"
                                       class="form-control" type="text" name="name"
                                       required
                                       uib-popover="El nombre del campo es requerido" popover-trigger="'mouseenter'"
                                       placeholder="Nombre" />

                            </div>
                            <div class="col-md-4">
                                <select class="tipoTramite-tipoDeDatos"
                                        name="fieldTypes"
                                        ng-model="field.type" ng-disabled="!editAvailable"
                                        ng-options="item.key as item.value for item in fieldTypes"></select>

                            </div>
                            <div class="col-md-3 tipoTramite-botonera">
                                <span class="fa fa-asterisk" ng-click="changeRequired(field)" ng-class="{asteriscoActivo : field.isRequired}" title="Marcar el campo como requerido"></span>
                                <span class="fa fa-trash" ng-click="events.deleteField(field)" ng-if="editAvailable" title="Eliminar campo"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-offset-2 col-md-8">
                        <button class="btn btn-satia btn-primario pull-right" ng-click="events.newField();" ng-if="editAvailable">Nuevo Campo</button>
                    </div>
                </div>
                <div class="col-md-offset-2 col-md-8 tipoTramite-campo">
                    <label>Documentos a adjuntar</label>
                    <hr style="margin-top:0"/>
                </div>
                <div ng-repeat="document in processTypeDocuments track by $index">
                    <div class="col-md-offset-2 col-md-8 tipoTramite-campo">
                        <div class="col-md-3">
                            <input ng-model="document.name" ng-disabled="!editAvailable"
                                   class="form-control" type="text" name="name"
                                   required
                                   uib-popover="El nombre del documento es requerido" popover-trigger="'mouseenter'"
                                   placeholder="Nombre" />

                        </div>
                        <div class="col-md-2 tipoTramite-botonera">
                            <span class="fa fa-trash" ng-click="events.deleteDocument(document)" ng-if="editAvailable"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2 col-md-8">
                    <button class="btn btn-satia btn-primario pull-right" ng-click="events.newDocument();" ng-if="editAvailable">Nuevo Documento</button>
                </div>
                <hr />
                <div class="col-md-offset-5 col-md-2">
                    <button class="btn btn-satia btn-primario pull-right" ng-click="events.onSaveClicked();">Guardar Cambios</button>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    <script src="~/Scripts/Site/ProcessType/ProcessType.Edit.js"></script>
}

LoginPoC/LoginPoC.Web/Areas/Admin/Views/ProcessType/Index.cshtml
@using LoginPoC.Model.User
@using LoginPoC.Web.Areas.Admin.Models;
@model ProcessTypeIndexViewModel

@{
    ViewBag.Title = "Tipos de Tramites";
}

<h2 class="tituloPrincipal readable">Tipos de Tr&aacute;mite</h2>
<hr class="tituloPrincipal" />
<div class="row">
    @using (Html.BeginForm("Index", "ProcessType", FormMethod.Get, new { area = "Admin" }))
    {
    <div class="col-xs-6 tipoTramite-buscar">
        <input type="text" placeholder="Buscar tipo de trámite" name="name" id="name" value="@Model.SearchByName"/>
        <button type="submit" class="fa fa-search"></button>
    </div>
    }
    @if (User.IsInRole(ApplicationUserRoles.Administrator))
    {
    <div class="col-xs-6 tipoTramite-crear">
        <p style="margin-bottom:0">
            <a href="@Url.Action("Create")" class="tipoTramite-textoCrear">
                Crear Nuevo Tipo de Trámite
                <span class="fa fa-plus" style="float:right; margin-right: 30px"></span>
            </a>
        </p>
     </div>
     }
</div>
<br />
<div class="row listado">
    @foreach (var item in Model.ProcessTypes)
    {
        <div class="col-xs-6">
            <p class="tipoTramite-item">
                <span class="tipoTramite-nombre readable">
                    @Html.DisplayFor(modelItem => item.Name)
                </span>
                <a href="#"><span class='fa fa-caret-down tipoTramite-itemBtn' id="tipoTramite-@item.Id"></span></a>
                @if (User.IsInRole(ApplicationUserRoles.Administrator))
                {
                    <a href="@Url.Action("Delete", new { id = item.Id })"><span class='fa fa-trash tipoTramite-itemBtn'></span></a>
                }
                @if (User.IsInRole(ApplicationUserRoles.Agent) || User.IsInRole(ApplicationUserRoles.Administrator))
                {
                    <a href="@Url.Action("Edit", new { id = item.Id })"><span class='fa fa-pencil tipoTramite-itemBtn'></span></a>
                }
            </p>
            <div hidden class="tipoTramite-descripcion" id="tipoTramite-@item.Id">
                <p class="tipoTramite-descripcion readable" style="overflow: hidden; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; max-height: 119px;">
                    @Html.DisplayFor(modelItem => item.Description)
                </p>
                @if (!String.IsNullOrEmpty(item.URLVideo))
                {
                    <iframe class="col-xs-12" height="297" style="padding: 5px 90px 15px 90px" src=@item.URLVideo frameborder="0" allowfullscreen></iframe>
                }
                <p class="tipoTramite-descripcion">
                    <a href="@Url.Action("Details",new { id = item.Id })" class="btn btn-satia btn-primario readable">Ver Detalles del trámite</a>
                    @if (User.IsInRole(ApplicationUserRoles.User))
                    {
                        <a href="@Url.Action("Create", "Process", new { area = "Common", id = item.Id } )" class="readable btn btn-satia btn-secundario pull-right">Iniciar tramite</a>
                    }
                </p>
            </div>

        </div>
    }
</div>
@section Scripts{
    <script src="~/Scripts/Site/ProcessType/ProcessType.Index.js"></script>
}