LoginPoC/LoginPoC.Web/Areas/Admin/Controllers/AgentController.cs
using AutoMapper;
using LoginPoC.Core.User;
using LoginPoC.Model.User;
using LoginPoC.Web.Areas.Admin.Models;
using LoginPoC.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LoginPoC.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = ApplicationUserRoles.Administrator)]
    public class AgentController : Controller
    {
        private ApplicationUserManager userManager;
        private ApplicationRoleManager roleManager;
        private IMapper mapper;

        public AgentController(ApplicationUserManager userManager, ApplicationRoleManager roleManager, IMapper mapper)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.mapper = mapper;
        }

        // GET: Agent        
        public async Task<ActionResult> Index(string name = null)
        {
            var agentRole = await this.roleManager.FindByNameAsync(ApplicationUserRoles.Agent);
            IQueryable<ApplicationUser> users = this.userManager.Users.Where(u => u.Roles.Any(r => r.RoleId == agentRole.Id))
                                                                      .OrderBy(u => u.LastName)
                                                                      .ThenBy(u => u.FirstName);

            if (!string.IsNullOrWhiteSpace(name))
            {
                users = users.Where(u => u.FirstName.Contains(name)
                                      || u.LastName.Contains(name)
                                      || u.UserName.Contains(name));
            }

            var vm = new AgentIndexViewModel()
            {
                SearchByName = name,
                Agents = this.mapper.Map<List<AgentViewModel>>(await users.ToListAsync())
            };

            if (this.Request.IsAjaxRequest())
            {
                return this.JsonNet(vm);
            }

            return View(vm);
        }

        //
        // GET: /Agent/Register
        public ActionResult Register()
        {
            return View("Edit", new AgentViewModel());
        }

        //
        // POST: /Agetn/Register
        [HttpPost]
        public async Task<ActionResult> Register(AgentViewModel vm)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    this.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return this.JsonNet(this.ModelState.AsModelErrorCollection());
                }

                var existing = await this.userManager.FindByEmailAsync(vm.Email);
                if (existing != null)
                {
                    this.Response.StatusCode = (int)HttpStatusCode.Conflict;
                    return this.JsonNet("Ya existe un usuario con el email especificado".AsModelErrorCollection());
                }

                var user = Mapper.Map<ApplicationUser>(vm);

                var result = await userManager.CreateAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddErrors(result);
                    this.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return this.JsonNet(ModelState.AsModelErrorCollection());
                }

                await userManager.AddToRoleAsync(user.Id, ApplicationUserRoles.Agent);
                await SendEmailConfirmationTokenToAgentAsync(user.Id, "Confirmar tu cuenta");

                return this.JsonNet(Mapper.Map<AgentViewModel>(user));
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return this.JsonNet(ex.AsModelErrorCollection());
            }
        }

        // GET: Agent/Edit
        public async Task<ActionResult> Edit(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound("No se encontro el agente especificado.");
            }

            var vm = mapper.Map<AgentViewModel>(user);

            return View(vm);
        }

        // POST: Agent/Edit
        [HttpPost]
        public async Task<ActionResult> Edit(AgentViewModel vm)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    this.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return this.JsonNet(this.ModelState.AsModelErrorCollection());
                }

                var user = await userManager.FindByIdAsync(vm.Id);
                mapper.Map(vm, user);

                var result = await userManager.UpdateAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddErrors(result);
                    this.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return this.JsonNet(this.ModelState.AsModelErrorCollection());
                }

                return this.JsonNet(vm);
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return this.JsonNet(ex.AsModelErrorCollection());
            }
        }

        private async Task<string> SendEmailConfirmationTokenToAgentAsync(string userID, string subject)
        {
            string code = await userManager.GenerateEmailConfirmationTokenAsync(userID);

            var callbackUrl = Url.Action("ConfirmEmailAndCreatePassword", "Account", new { area = "Security", userId = userID, code = code }, protocol: Request.Url.Scheme);
            await userManager.SendEmailAsync(userID, subject, "Confirma tu cuenta y crea una contraseña haciendo <a href=\"" + callbackUrl + "\">click aquí</a>");

            return callbackUrl;
        }
    }
}

LoginPoC/LoginPoC.Web/Areas/Admin/Controllers/TeamController.cs
using AutoMapper;
using LoginPoC.Core.Teams;
using LoginPoC.Model.Teams;
using LoginPoC.Model.User;
using LoginPoC.Web.Areas.Admin.Models;
using LoginPoC.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LoginPoC.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = ApplicationUserRoles.Administrator)]
    public class TeamController : Controller
    {
        private readonly ITeamService teamService;
        private readonly IMapper mapper;

        public TeamController(ITeamService teamService, IMapper mapper)
        {
            this.teamService = teamService;
            this.mapper = mapper;
        }

        // GET: Team
        public async Task<ActionResult> Index(string name = null)
        {
            var teams = await this.teamService.SearchAsync(name);
            var vm = new TeamIndexViewModel()
            {
                Teams = this.mapper.Map<List<TeamViewModel>>(teams),
                SearchByName = name
            };

            return View(vm);
        }

        // GET: Team/Edit/{id}
        public ActionResult Edit(int id)
        {
            var team = this.teamService.GetById(id);
            if (team == null)
            {
                return HttpNotFound("No se encontro el equipo especificado");
            }

            var vm = this.mapper.Map<TeamViewModel>(team);
            return View(vm);
        }

        // POST: Team/Edit/{id}
        [HttpPost]
        public ActionResult Edit(TeamViewModel vm)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    this.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return this.JsonNet(this.ModelState.AsModelErrorCollection());
                }

                var team = this.mapper.Map<Team>(vm);

                this.teamService.Update(team);

                return this.JsonNet(vm);
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return this.JsonNet(ex.AsModelErrorCollection());
            }
        }

        // GET: Team/Create
        public ActionResult Create()
        {
            return View("Edit", new TeamViewModel());
        }

        // POST: Team/Create
        [HttpPost]
        public ActionResult Create(TeamViewModel vm)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    this.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return this.JsonNet(this.ModelState.AsModelErrorCollection());
                }

                var team = this.mapper.Map<Team>(vm);

                this.teamService.Add(team);

                return this.JsonNet(vm);
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return this.JsonNet(ex.AsModelErrorCollection());
            }
        }

        // GET: Team/Delete/{id}
        public ActionResult Delete(int id)
        {
            var team = this.teamService.GetById(id);
            if (team == null)
            {
                return HttpNotFound("No se encontro el equipo especificado");
            }

            var vm = this.mapper.Map<TeamViewModel>(team);
            return View(vm);
        }

        // POST: Team/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                this.teamService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return this.JsonNet(ex.AsModelErrorCollection());
            }
        }
    }
}

LoginPoC/LoginPoC.Web/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

LoginPoC/LoginPoC.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using LoginPoC.Model.User
@using AutoMapper;
@using LoginPoC.Core.User;
@using LoginPoC.Web.Areas.Common.Models;
@using LoginPoC.Web.Helpers;
@using Microsoft.AspNet.Identity;
@using Microsoft.Owin.Security;
@using System;
@using System.Threading.Tasks;
@using System.Web;
@using System.Web.Mvc;
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using Newtonsoft.Json;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta fa
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SATIA</title>
    <script src="https://code.responsivevoice.org/responsivevoice.js"></script>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    @RenderSection("styles", required: false)

    <style type="text/css">
        [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
            display: none !important;
        }
    </style>

</head>
<body ng-app="app">
    <div class="navbar navbar-inverse navbar-fixed-top header">
        <div class="container">
            <div class="navbar-header">
                <a href="@Url.Action("Index", "Home", new { area = "Common" })"><img src="~/Content/Images/Logo-header-01.png"/></a>
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_MenuPartial")
            </div>
        </div>
    </div>
    <div class="container body-content ng-cloak">
        @RenderBody()
    </div>
    <footer class="text-right">
        <div id="google_translate_element" style="float:left; margin: 12px 10px"></div>
        <p class="readable">Medrano 951 (C1179AAQ) C.A.B.A. Tel: (54 11) 4867-7500 &copy; @DateTime.Now.Year - G407</p> 

            
        <script type="text/javascript">
            function googleTranslateElementInit() {
                new google.translate.TranslateElement({ pageLanguage: 'es', includedLanguages: 'es,en,fr', layout: google.translate.TranslateElement.InlineLayout.SIMPLE }, 'google_translate_element');
            }
            function readCookie(name) {
                var c = document.cookie.split('; '),
                    cookies = {}, i, C;

                for (i = c.length - 1; i >= 0; i--) {
                    C = c[i].split('=');
                    cookies[C[0]] = C[1];
                }

                return cookies[name];
            }

            function languageToRead(selectedGoogleLanguage) {
                if (selectedGoogleLanguage == undefined) {
                    return 'Spanish Latin American Female';
                }
                switch (selectedGoogleLanguage.substr(4)) {
                    case 'en':
                        return 'UK English Female';
                    case 'es':
                        return 'Spanish Latin American Female';
                    case 'fr':
                        return 'French Female';
                }
            }

            @if (User.Identity.GetCanRead() && User.Identity.IsAuthenticated) {
                <text>
                $(document).on('mouseover', '.readable', function (e) {
                    responsiveVoice.speak($('.readable:hover').text(), languageToRead(readCookie('googtrans')));
                });
                </text>
            }
        </script>
        <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

    </footer>

    <script src="https://ft-polyfill-service.herokuapp.com/v2/polyfill.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LoginPoC/LoginPoC.Web/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNet.Identity
@using LoginPoC.Model.User
<ul class="nav navbar-nav">
    @if (User.Identity.IsAuthenticated)
    {
        <li class="readable">@Html.ActionLink("Tipos de trámites", "Index", "ProcessType", new { area = "Admin" }, new { @class = "header-btn-link" })</li>

        if (User.IsInRole(ApplicationUserRoles.User))
        {
            <li class="readable">@Html.ActionLink("Trámites Guardados", "MyProcesses", "Process", new { area = "Common" }, new { @class = "header-btn-link" })</li>
        }

        if (User.IsInRole(ApplicationUserRoles.Agent) || User.IsInRole(ApplicationUserRoles.Administrator))
        {
            <li>@Html.ActionLink("Trámites", "Index", "Process", new { area = "Common" }, new { @class = "header-btn-link" })</li>
        }

        if(User.IsInRole(ApplicationUserRoles.Administrator))
        {
            <li>@Html.ActionLink("Asesores", "Index", "Agent", new { area = "Admin" }, new { @class = "header-btn-link" })</li>
            <li>@Html.ActionLink("Equipos", "Index", "Team", new { area = "Admin" }, new { @class = "header-btn-link" })</li>
        }
    }
</ul>

@Html.Partial("_LoginPartial")